#! /bin/sh
PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin:
runlevel=S
prevlevel=N
umask 022
export PATH runlevel prevlevel

#
#	Trap CTRL-C &c only in this shell so we can interrupt subprocesses.
#
trap ":" INT QUIT TSTP
/bin/hostname TE6410

/bin/mount -n -t proc none /proc
/bin/mount -n -t sysfs none /sys
/bin/mount -n -t usbfs none /proc/bus/usb
/bin/mount -t ramfs none /dev

echo /sbin/mdev > /proc/sys/kernel/hotplug
/sbin/mdev -s
/bin/hotplug
# mounting file system specified in /etc/fstab
mkdir -p /dev/pts
mkdir -p /dev/shm
/bin/mount -n -t devpts none /dev/pts -o mode=0622
/bin/mount -n -t tmpfs tmpfs /dev/shm
/bin/mount -n -t ramfs none /tmp
/bin/mount -n -t ramfs none /var
mkdir -p /var/empty
mkdir -p /var/log
mkdir -p /var/log/boa
mkdir -p /var/lock
mkdir -p /var/run
mkdir -p /var/tmp

/sbin/hwclock -s -f /dev/rtc

syslogd
/etc/rc.d/init.d/netd start
echo "                        " > /dev/tty1
echo "Starting networking..." > /dev/tty1
echo "*************************************" > /dev/tty1
echo "     http://www.witech.com.cn        " > /dev/tty1
echo "*************************************" > /dev/tty1
echo "*************************************" 
echo "     http://www.witech.com.cn        " 
echo "*************************************" 

mkdir /mnt/disk
mount -t yaffs2 /dev/mtdblock3 /mnt/disk

/sbin/ifconfig lo 127.0.0.1
/etc/init.d/ifconfig-eth0

#================================================================================
#
#  ____  ____  ____    ____ ___  _   _      ____ ___  _
# /  _ \/  _ \/  _ \  /  _ \\  \//  / \  /|/   _\\  \//
# | / \|| | \|| | \|  | | // \  /   | |  |||  /   \  / 
# | |-||| |_/|| |_/|  | |_\\ / /    | |/\|||  \_  /  \ 
# \_/ \|\____/\____/  \____//_/     \_/  \|\____//__/\\ --- v0.3.0
#                                                     
#================================================================================
ORT3000_PATH=/ort3000

PATH_UPDATE=$ORT3000_PATH/update
PATH_CODE=$ORT3000_PATH/code
PATH_DATA=$ORT3000_PATH/data

# mount partition to ort3000 folder
mount -t yaffs2 /dev/mtdblock4 $PATH_UPDATE
mount -t yaffs2 /dev/mtdblock2 $PATH_CODE
mount -t yaffs2 /dev/mtdblock5 $PATH_DATA

# mount usb                                            
mkdir -p /udisk                                     
mount -t vfat /dev/udisk /udisk

# mount sdcard                                         
#mount -t vfat /dev/sdcard /mnt/sdcard                 

# rout.add.default.gw                                 
#route add default gw 192.168.1.1

# config.eth0:1                  
ifconfig   eth0:1   172.16.16.129 netmask 255.255.255.248
ifconfig eth0:1 up 

# updata
cd $PATH_UPDATE
./update.sh $ORT3000_PATH

# insmod driver
sleep 6
insmod $PATH_CODE/driver/sierra.ko
insmod $PATH_CODE/driver/adc.ko
insmod $PATH_CODE/driver/forlinx_18b20.ko 
insmod $PATH_CODE/driver/serial_vk32xx.ko
insmod $PATH_CODE/driver/ort3000c_watch_dog.ko
insmod $PATH_CODE/driver/ort3000c_io.ko 
insmod $PATH_CODE/driver/battery_detect.ko 
insmod $PATH_CODE/driver/mcp251x.ko

# set can bitrate
up link set can0 up type can bitrate 250000

# run watch_dog                                
#$PATH_CODE/driver/watch_dog_test.bin &

# run collect
demo.bin $PATH_CODE/collect/bin/wcx_collect.bin

# gsm_online                     
cd $PATH_CODE/gsm_online
./gsm_online.bin

# vpn_online                     
cd $PATH_CODE/vpn_online
#./vpn_online.bin

# run.server_rtu_setup_arm
demo.bin $PATH_CODE/server_rtu_setup/server_rtu_setup_arm.bin

# install crond
install -m 755 -d /var/spool/cron/crontabs
install -m 755 /usr/bin/root /var/spool/cron/crontabs/

# run crond
#crond &

# run ftp
mkdir -p /usr/share/empty
mkdir -p /var/ftp
vsftpd &

# recode boot times
echo starting at $(date) >> /etc/start_times.log

# run ssh
/sbin/sshd
